apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvaultsecretstore
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "groffekeyvault202609"
  - name: azureTenantId
    value: "MICROSOFT_ENTRA_TENANT_ID"
  - name: azureClientId
    value: "MICROSOFT_ENTRA_APP_REGISTRATION_CLIENT_ID"
  - name: azureClientSecret
    value : "MICROSOFT_ENTRA_APP_REGISTRATION_CLIENT_SECRET"